CoinTrail/CoinTrail/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("expense_track.urls")),
    path('admin/', admin.site.urls),
]

CoinTrail/expense_track/urls.py
from django.urls import path

from . import views

app_name = "expense_track"
urlpatterns = [
    # ex: /expense_track/
    path("transactions/", views.index, name="index"),
    # ex: /expense_track/5/details
    path("transactions/<int:transaction_id>/", views.details, name="details"),
    # ex: /expense_track/summary
    path("summary/", views.summary, name="summary"),
    # ex: /expense_track/test
    path("test/", views.test, name="test")
]

CoinTrail/expense_track/models.py
# Importing libraries
from decimal import Decimal
from datetime import date
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.db.models import Sum


# Creates a model manager for transactions
class TransactionManager(models.Manager):
    # Gets the total expenses incurred to date
    def sort_income_accounts(self, income_account):
        return self.filter(income_account=income_account).aggregate(expense=Sum("expense", default=0))["expense"]

    # Lists all the income accounts found in the transaction history.
    def get_income_accounts(self):
        all_income_accounts = set(self.values_list('income_account', flat=True))    # set() here removes duplicates.
        return all_income_accounts


# Transaction class to handle new transactions
class Transaction(models.Model):
    date = models.DateTimeField(default=timezone.now, blank=False)
    income_account = models.CharField(blank=False, max_length=100)
    expense = models.DecimalField(
        default=10,
        blank=False,
        decimal_places=2,
        max_digits=10,
        validators=[MinValueValidator(Decimal("0.01")), ]
    )
    income = models.DecimalField(
        default=10,
        blank=False,
        decimal_places=2,
        max_digits=10,
        validators=[MinValueValidator(Decimal("0.01")), ]
    )

    description = models.CharField(blank=True, max_length=200)
    expense_account = models.CharField(blank=False, max_length=100)
    category = models.CharField(blank=True, max_length=100)
    subcategory = models.CharField(blank=True, max_length=100)

    objects = TransactionManager()

    # Returns the total change based on the income & expense values
    def get_total(self):
        total = self.income - self.expense
        return round(total, 2)

    # Provides a detailed description of the transaction
    def details(self):
        output = (
                "Transaction: " + str(self.id)
                + "\nDate: " + self.date.strftime("%d/%m/%Y")
                + "\nIncome account: " + self.income_account
                + "\nExpense: " + str(self.expense)
                + "\nIncome: " + str(self.income)
                + "\nTotal: " + str(self.get_total())
                + "\nDescription: " + self.description
                + "\nExpense account: " + self.expense_account
                + "\nCategory: " + self.category
                + "\nSubcategory: " + self.subcategory
        )
        return output

    # A simplified transaction summary for human identification of a transaction.
    def __str__(self):
        output = (
                "Transaction: " + str(self.id)
                + " | Date: " + self.date.strftime("%d/%m/%Y")
        )
        return output

CoinTrail/expense_track/views.py
# from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from .models import Transaction


# Shows an index of the most recent 5 transactions.
def index(request):
    latest_transaction_list = Transaction.objects.order_by("-date")[:5]
    context = {"latest_transaction_list": latest_transaction_list}
    return render(request, "expense_track/index.html", context)


# Shows the expanded details of a single transaction.
def details(request, transaction_id):
    selected_transaction = get_object_or_404(Transaction, pk=transaction_id)
    return render(request, "expense_track/details.html",
                  {"transaction": selected_transaction.details}, content_type="text/plain")


def summary(request):
    full_transaction_list = Transaction.objects.sort_income_accounts("MAE")
    return HttpResponse(full_transaction_list)


def test(request):
    return render(request, "expense_track/test.html",
                  {"income_accounts": Transaction.objects.get_income_accounts()})

CoinTrail/expense_track/templates/expense_track/details.html
{{ transaction }}

CoinTrail/expense_track/templates/expense_track/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon_3.png' %}">
    <title>Title</title>
</head>

<body>

{% if latest_transaction_list %}
    <ul>
    {% for transaction in latest_transaction_list %}
        <li><a href="{% url 'expense_track:details' transaction.id %}">{{ transaction }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No transactions are available.</p>
{% endif %}

</body>
</html>

CoinTrail/expense_track/templates/expense_track/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon_3.png' %}">
    <title>Title</title>
</head>

<body>
    <form action="{% url 'expense_track:test' %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>Pick an account to view.</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for account in income_accounts %}
        <input type="radio" name="account" id="account{{ forloop.counter }}" value="{{ account }}">
        <label for="account{{ forloop.counter }}">{{ account }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
</body>
</html>